return {
  -- COMMAND LIST
  {name = " CHEAT: Add Gold (Custom Amount)", cmd = "INPUT_GOLD"},
  {name = " CHEAT: Add Talents (Custom Amount)", cmd = "INPUT_TALENTS"},
  {name = " CHEAT: Map Reveal Range", cmd = "INPUT_MAP"},
  {name = " CHEAT: Battle Fade Speed", cmd = "INPUT_FADE"},
  {name = " CHEAT: Level Up", cmd = "dm_levelup"},

  -- STEEL SWORDS
  {name = " STEEL: Witcher Steel Sword", cmd = "dm_spawnitem it_stlswd_001"},
  {name = " STEEL: Temerian Steel", cmd = "dm_spawnitem it_stlswd_005"},
  {name = " STEEL: Rusty Sword", cmd = "dm_spawnitem it_stlswd_006"},
  {name = " STEEL: Sword of the Order", cmd = "dm_spawnitem it_stlswd_007"},
  {name = " STEEL: Illegal Sword", cmd = "dm_spawnitem it_stlswd_008"},
  {name = " STEEL: Holy Sword of the Order", cmd = "dm_spawnitem it_stlswd_009"},
  {name = " STEEL: Elven Sword Blue Mtns", cmd = "dm_spawnitem it_stlswd_010"},
  {name = " STEEL: Ceremonial Deithwen", cmd = "dm_spawnitem it_stlswd_011"},
  {name = " STEEL: Mahakaman Rune Sihill", cmd = "dm_spawnitem it_stlswd_012"},
  {name = " STEEL: Dol Blathanna Rune", cmd = "dm_spawnitem it_stlswd_013"},
  {name = " STEEL: Harvall", cmd = "dm_spawnitem it_stlswd_014"},
  {name = " STEEL: Gwalhir", cmd = "dm_spawnitem it_stlswd_015"},
  {name = " STEEL: D'yaebl", cmd = "dm_spawnitem it_stlswd_016"},
  {name = " STEEL: Ard'aenye (Best)", cmd = "dm_spawnitem it_stlswd_017"},
  {name = " STEEL: Meteorite (Red-Red-Blue)", cmd = "dm_spawnitem it_stlswd_rrb"},
  {name = " STEEL: Meteorite (Blue-Blue-Blue)", cmd = "dm_spawnitem it_stlswd_bbb"},
  {name = " STEEL: Meteorite (Yel-Yel-Yel)", cmd = "dm_spawnitem it_stlswd_yyy"},
  {name = " STEEL: Meteorite (Blue-Yel-Yel)", cmd = "dm_spawnitem it_stlswd_byy"},
  {name = " STEEL: Meteorite (Yel-Yel-Red)", cmd = "dm_spawnitem it_stlswd_yyr"},
  {name = " STEEL: Meteorite (Red-Red-Red)", cmd = "dm_spawnitem it_stlswd_rrr"},
  {name = " STEEL: Meteorite (Red-Blue-Blue)", cmd = "dm_spawnitem it_stlswd_rbb"},
  {name = " STEEL: Meteorite (Yel-Red-Red)", cmd = "dm_spawnitem it_stlswd_yrr"},
  {name = " STEEL: Meteorite (Blue-Blue-Yel)", cmd = "dm_spawnitem it_stlswd_bby"},
  {name = " STEEL: Meteorite (Red-Blue-Yel)", cmd = "dm_spawnitem it_stlswd_rby"},

  -- SILVER SWORDS
  {name = " SILVER: Witcher Silver 1", cmd = "dm_spawnitem it_svswd_001"},
  {name = " SILVER: Aerondight (Best)", cmd = "dm_spawnitem it_svswd_005"},
  {name = " SILVER: Moonblade", cmd = "dm_spawnitem it_svswd_006"},
  {name = " SILVER: Rune (Sun-Sun-Sun)", cmd = "dm_spawnitem it_svswd_sss"},
  {name = " SILVER: Rune (Earth-Earth-Sun)", cmd = "dm_spawnitem it_svswd_ees"},
  {name = " SILVER: Rune (Moon-Earth-Earth)", cmd = "dm_spawnitem it_svswd_mee"},
  {name = " SILVER: Rune (Moon-Moon-Earth)", cmd = "dm_spawnitem it_svswd_mme"},
  {name = " SILVER: Rune (Sun-Sun-Moon)", cmd = "dm_spawnitem it_svswd_ssm"},
  {name = " SILVER: Rune (Sun-Moon-Moon)", cmd = "dm_spawnitem it_svswd_smm"},
  {name = " SILVER: Rune (Earth-Sun-Sun)", cmd = "dm_spawnitem it_svswd_ess"},
  {name = " SILVER: Rune (Moon-Moon-Moon)", cmd = "dm_spawnitem it_svswd_mmm"},
  {name = " SILVER: Rune (Sun-Moon-Earth)", cmd = "dm_spawnitem it_svswd_sme"},
  {name = " SILVER: Rune (Earth-Earth-Earth)", cmd = "dm_spawnitem it_svswd_eee"},

  -- OTHER WEAPONS
  {name = " WEAPON: Temerian Iron Dagger", cmd = "dm_spawnitem m0_it_dgr01"},
  {name = " WEAPON: Temerian Steel Dagger", cmd = "dm_spawnitem m0_it_dgr02"},
  {name = " WEAPON: Assassin Dagger", cmd = "dm_spawnitem m0_it_dgr03"},
  {name = " WEAPON: Mahakaman Dagger", cmd = "dm_spawnitem m0_it_dgr04"},
  {name = " WEAPON: Deithwen Dagger", cmd = "dm_spawnitem m0_it_dgr05"},
  {name = " WEAPON: Mahakaman Rune Dagger", cmd = "dm_spawnitem m0_it_dgr06"},
  {name = " WEAPON: Two-Handed Steel Axe", cmd = "dm_spawnitem m0_it_laxe02"},
  {name = " WEAPON: Temerian Iron Axe", cmd = "dm_spawnitem m0_it_saxe02"},
  {name = " WEAPON: Temerian Steel Axe", cmd = "dm_spawnitem m0_it_saxe03"},
  {name = " WEAPON: Mahakaman Dwarf Axe", cmd = "dm_spawnitem m0_it_saxe06"},
  {name = " WEAPON: Mt Carbon Rune Axe", cmd = "dm_spawnitem m0_it_saxe07"},
  {name = " WEAPON: Holy Axe of Order", cmd = "dm_spawnitem m0_it_saxe08"},
  {name = " WEAPON: Order Battle Hammer", cmd = "dm_spawnitem m0_it_sclub03"},
  {name = " WEAPON: Holy Battle Hammer", cmd = "dm_spawnitem m0_it_sclub04"},
  {name = " WEAPON: Mahakaman Hammer", cmd = "dm_spawnitem m0_it_sclub05"},
  {name = " WEAPON: Torch", cmd = "dm_spawnitem m0_it_torch01"},

  -- ARMOR
  {name = " ARMOR: Trews and Shirt", cmd = "dm_spawnitem it_witcharm_001"},
  {name = " ARMOR: Studded Leather", cmd = "dm_spawnitem it_witcharm_002"},
  {name = " ARMOR: Excellent Leather", cmd = "dm_spawnitem it_witcharm_003"},
  {name = " ARMOR: Raven's Armor (Neutral)", cmd = "dm_spawnitem it_witcharm_004"},
  {name = " ARMOR: Raven's Armor (Order)", cmd = "dm_spawnitem it_witcharm_005"},
  {name = " ARMOR: Raven's Armor (Elf)", cmd = "dm_spawnitem it_witcharm_006"},
  {name = " ARMOR: Armor 5c", cmd = "dm_spawnitem it_witcharm_007"},

  -- POTIONS
  {name = " POTION: Swallow (Heal)", cmd = "dm_spawnitem it_potion_004"},
  {name = " POTION: Tawny Owl (Stam)", cmd = "dm_spawnitem it_potion_003"},
  {name = " POTION: White Honey (Detox)", cmd = "dm_spawnitem it_potion_005"},
  {name = " POTION: Blizzard", cmd = "dm_spawnitem it_potion_019"},
  {name = " POTION: Cat", cmd = "dm_spawnitem it_potion_013"},
  {name = " POTION: Thunderbolt", cmd = "dm_spawnitem it_potion_023"},
  {name = " POTION: White Raffard's", cmd = "dm_spawnitem it_potion_010"},
  {name = " POTION: Willow", cmd = "dm_spawnitem it_potion_024"},
  {name = " POTION: Black Blood", cmd = "dm_spawnitem it_potion_020"},
  {name = " POTION: Wolf", cmd = "dm_spawnitem it_potion_017"},
  {name = " POTION: Full Moon", cmd = "dm_spawnitem it_potion_022"},
  {name = " POTION: White Gull", cmd = "dm_spawnitem it_potion_002"},
  {name = " POTION: Bindweed", cmd = "dm_spawnitem it_potion_021"},
  {name = " POTION: De Vries Extract", cmd = "dm_spawnitem it_potion_025"},
  {name = " POTION: Golden Oriole", cmd = "dm_spawnitem it_potion_008"},
  {name = " POTION: Kiss", cmd = "dm_spawnitem it_potion_018"},
  {name = " POTION: Maribor Forest", cmd = "dm_spawnitem it_potion_009"},
  {name = " POTION: Petri's Philter", cmd = "dm_spawnitem it_potion_012"},
  {name = " POTION: Shrike", cmd = "dm_spawnitem it_potion_016"},
  {name = " POTION: Wolverine", cmd = "dm_spawnitem it_potion_011"},
  {name = " POTION: Wives' Tears", cmd = "dm_spawnitem it_potion_006"},
  {name = " POTION: Perfume", cmd = "dm_spawnitem it_potion_007"},
  {name = " POTION: Fistech", cmd = "dm_spawnitem it_potion_014"},

  -- MUTAGENS
  {name = " MUTAGEN: Striga's Urge", cmd = "dm_spawnitem it_potion_107"},
  {name = " MUTAGEN: Dagon Sap", cmd = "dm_spawnitem it_potion_101"},
  {name = " MUTAGEN: Golem's Pith", cmd = "dm_spawnitem it_potion_104"},
  {name = " MUTAGEN: Hellhound's Soul", cmd = "dm_spawnitem it_potion_106"},
  {name = " MUTAGEN: Kikimore's Ire", cmd = "dm_spawnitem it_potion_106"},
  {name = " MUTAGEN: Koshchey's Core", cmd = "dm_spawnitem it_potion_108"},
  {name = " MUTAGEN: Werewolf's Wrath", cmd = "dm_spawnitem it_potion_102"},
  {name = " MUTAGEN: Zeugl's Vigor", cmd = "dm_spawnitem it_potion_109"},
  {name = " MUTAGEN: Viziman Champion", cmd = "dm_spawnitem it_potion_152"},
  {name = " MUTAGEN: Frightener's Vision", cmd = "dm_spawnitem it_potion_105"},

  -- UPGRADES
  {name = " UPGRADE: Red Meteorite", cmd = "dm_spawnitem it_upgrcomp_001"},
  {name = " UPGRADE: Blue Meteorite", cmd = "dm_spawnitem it_upgrcomp_002"},
  {name = " UPGRADE: Yellow Meteorite", cmd = "dm_spawnitem it_upgrcomp_003"},
  {name = " UPGRADE: Sun Rune", cmd = "dm_spawnitem it_upgrcomp_004"},
  {name = " UPGRADE: Earth Rune", cmd = "dm_spawnitem it_upgrcomp_005"},
  {name = " UPGRADE: Moon Rune", cmd = "dm_spawnitem it_upgrcomp_006"},

  -- OILS & GREASE
  {name = " OIL: Argentia", cmd = "dm_spawnitem it_grease_004"},
  {name = " OIL: Blade Grease", cmd = "dm_spawnitem it_grease_002"},
  {name = " OIL: Crinfrid Oil", cmd = "dm_spawnitem it_grease_005"},
  {name = " OIL: Diamond Dust", cmd = "dm_spawnitem it_grease_021"},
  {name = " OIL: Grindstone", cmd = "dm_spawnitem it_grease_020"},
  {name = " OIL: Hanged Man Venom", cmd = "dm_spawnitem it_grease_003"},
  {name = " OIL: Insectoid Oil", cmd = "dm_spawnitem it_grease_010"},
  {name = " OIL: Necrophage Oil", cmd = "dm_spawnitem it_grease_008"},
  {name = " OIL: Ornithosaur Oil", cmd = "dm_spawnitem it_grease_007"},
  {name = " OIL: Specter Oil", cmd = "dm_spawnitem it_grease_001"},
  {name = " OIL: Vampire Oil", cmd = "dm_spawnitem it_grease_009"},
  {name = " OIL: Whetstone", cmd = "dm_spawnitem it_grease_019"},
  {name = " OIL: Perun Rune Stone", cmd = "dm_spawnitem it_grease_024"},
  {name = " OIL: Savrog Rune Stone", cmd = "dm_spawnitem it_grease_023"},
  {name = " OIL: Vodon Rune Stone", cmd = "dm_spawnitem it_grease_022"},

  -- BOMBS
  {name = " BOMB: King and Queen", cmd = "dm_spawnitem it_bomb_001"},
  {name = " BOMB: Devil's Puffball", cmd = "dm_spawnitem it_bomb_002"},
  {name = " BOMB: Zerrikanian Sun", cmd = "dm_spawnitem it_bomb_003"},
  {name = " BOMB: Samum", cmd = "dm_spawnitem it_bomb_004"},
  {name = " BOMB: Dragon's Dream", cmd = "dm_spawnitem it_bomb_005"},

  -- TROPHIES
  {name = " TROPHY: Teyu Head", cmd = "dm_spawnitem it_trophy_001"},
  {name = " TROPHY: Alghoul Head", cmd = "dm_spawnitem it_trophy_002"},
  {name = " TROPHY: Cockatrice Head", cmd = "dm_spawnitem it_trophy_003"},
  {name = " TROPHY: Wolf Head", cmd = "dm_spawnitem it_trophy_004"},
  {name = " TROPHY: Female Wyvern", cmd = "dm_spawnitem it_trophy_005"},
  {name = " TROPHY: Cemetaur Head", cmd = "dm_spawnitem it_trophy_006"},
  {name = " TROPHY: Archespore Head", cmd = "dm_spawnitem it_trophy_007"},
  {name = " TROPHY: Garkain Head", cmd = "dm_spawnitem it_trophy_008"},
  {name = " TROPHY: Bruxa Head", cmd = "dm_spawnitem it_trophy_009"},
  {name = " TROPHY: Drowned Dead", cmd = "dm_spawnitem it_trophy_010"},

  -- BOOKS & SCROLLS
  {name = " BOOK: Ain Soph Aur", cmd = "dm_spawnitem it_scroll_009"},
  {name = " BOOK: Book of Animals", cmd = "dm_spawnitem it_scroll_313"},
  {name = " BOOK: Swamp Monsters", cmd = "dm_spawnitem it_scroll_301"},
  {name = " BOOK: The Last Wish", cmd = "dm_spawnitem it_scroll_314"},
  {name = " BOOK: Ithlinne's Prophecy", cmd = "dm_spawnitem it_scroll_227"},
  {name = " BOOK: Spell - Aard", cmd = "dm_spawnitem m0_it_spell02"},
  {name = " BOOK: Formula - White Raffard", cmd = "dm_spawnitem it_scroll_114"},
  {name = " BOOK: Formula - Maribor Forest", cmd = "dm_spawnitem it_scroll_116"},
  {name = " BOOK: Guide to Vizima", cmd = "dm_spawnitem it_scroll_213"},
  {name = " BOOK: Small Book of Minerals", cmd = "dm_spawnitem it_scroll_332"},
  {name = " BOOK: Against Nonhumans", cmd = "dm_spawnitem it_scroll_217"},
  {name = " BOOK: Invitation to Magic", cmd = "dm_spawnitem it_scroll_210"},
  {name = " BOOK: Animating Inanimate", cmd = "dm_spawnitem it_scroll_318"},
  {name = " BOOK: Ars Amandi", cmd = "dm_spawnitem it_scroll_220"},
  {name = " BOOK: Ballads", cmd = "dm_spawnitem it_scroll_223"},
  {name = " BOOK: Barghests", cmd = "dm_spawnitem it_scroll_304"},
  {name = " BOOK: Basics of Alchemy", cmd = "dm_spawnitem it_scroll_219"},
  {name = " BOOK: Cults and Religions", cmd = "dm_spawnitem it_scroll_218"},
  {name = " BOOK: Curses and Cursed", cmd = "dm_spawnitem it_scroll_310"},
  {name = " BOOK: Dagon Sap", cmd = "dm_spawnitem it_scroll_155"},
  {name = " BOOK: Dice Collector Diary", cmd = "dm_spawnitem it_scroll_224"},
  {name = " BOOK: Disenchanting Striga", cmd = "dm_spawnitem it_scroll_225"},
  {name = " BOOK: Elder Blood", cmd = "dm_spawnitem it_scroll_226"},
  {name = " BOOK: Experiment Notes", cmd = "dm_spawnitem it_scroll_311"},
  {name = " BOOK: Fairytales", cmd = "dm_spawnitem it_scroll_222"},
  {name = " BOOK: Feainnewedd", cmd = "dm_spawnitem it_scroll_330"},
  {name = " BOOK: Field Plants", cmd = "dm_spawnitem it_scroll_325"},
  {name = " BOOK: Foreign Lands", cmd = "dm_spawnitem it_scroll_214"},
  {name = " BOOK: Forensic Medicine", cmd = "dm_spawnitem it_scroll_211"},
  {name = " BOOK: Frightener Vision", cmd = "dm_spawnitem it_scroll_150"},
  {name = " BOOK: Golem Pith", cmd = "dm_spawnitem it_scroll_152"},
  {name = " BOOK: Greater Brothers", cmd = "dm_spawnitem it_scroll_312"},
  {name = " BOOK: Hellhound Soul", cmd = "dm_spawnitem it_scroll_151"},
  {name = " BOOK: Hymns of Madness", cmd = "dm_spawnitem it_scroll_231"},
  {name = " BOOK: Kikimore Ire", cmd = "dm_spawnitem it_scroll_154"},
  {name = " BOOK: Koshchey Core", cmd = "dm_spawnitem it_scroll_157"},
  {name = " BOOK: Lara's Gift", cmd = "dm_spawnitem it_scroll_204"},
  {name = " BOOK: Monstrum", cmd = "dm_spawnitem it_scroll_201"},
  {name = " BOOK: Ornithosaurs", cmd = "dm_spawnitem it_scroll_303"},
  {name = " BOOK: Physiologus", cmd = "dm_spawnitem it_scroll_319"},
  {name = " BOOK: Plants of Barren", cmd = "dm_spawnitem it_scroll_329"},
  {name = " BOOK: Ritual Plants", cmd = "dm_spawnitem it_scroll_328"},
  {name = " BOOK: Samum", cmd = "dm_spawnitem it_scroll_113"},
  {name = " BOOK: Secrets Southern Masters", cmd = "dm_spawnitem it_scroll_111"},
  {name = " BOOK: Shadow People", cmd = "dm_spawnitem it_scroll_202"},
  {name = " BOOK: Sorceresses", cmd = "dm_spawnitem it_scroll_215"},
  {name = " BOOK: Specters Wraiths", cmd = "dm_spawnitem it_scroll_305"},
  {name = " BOOK: Striga's Urge", cmd = "dm_spawnitem it_scroll_156"},
  {name = " BOOK: Subterranean Plants", cmd = "dm_spawnitem it_scroll_326"},
  {name = " BOOK: Swamp Plants", cmd = "dm_spawnitem it_scroll_327"},
  {name = " BOOK: Aftermath of War", cmd = "dm_spawnitem it_scroll_221"},
  {name = " BOOK: Druid Herbarium", cmd = "dm_spawnitem it_scroll_331"},
  {name = " BOOK: Flower and Flame", cmd = "dm_spawnitem it_scroll_206"},
  {name = " BOOK: Frightener", cmd = "dm_spawnitem it_scroll_315"},
  {name = " BOOK: Great Book Minerals", cmd = "dm_spawnitem it_scroll_333"},
  {name = " BOOK: History of World", cmd = "dm_spawnitem it_scroll_208"},
  {name = " BOOK: Kingdom of Temeria", cmd = "dm_spawnitem it_scroll_216"},
  {name = " BOOK: Road of No Return", cmd = "dm_spawnitem it_scroll_316"},
  {name = " BOOK: Story of Lara Dorren", cmd = "dm_spawnitem it_scroll_203"},
  {name = " BOOK: Temptation of Fire", cmd = "dm_spawnitem it_scroll_230"},
  {name = " BOOK: Fear and Loathing I", cmd = "dm_spawnitem it_scroll_308"},
  {name = " BOOK: Fear and Loathing II", cmd = "dm_spawnitem it_scroll_309"},
  {name = " BOOK: Wonderful Insectoids", cmd = "dm_spawnitem it_scroll_307"},
  {name = " BOOK: Transmutations", cmd = "dm_spawnitem it_scroll_205"},
  {name = " BOOK: Vampires Facts", cmd = "dm_spawnitem it_scroll_306"},
  {name = " BOOK: Werewolf Wrath", cmd = "dm_spawnitem it_scroll_153"},
  {name = " BOOK: Zerrikanian Alchemy", cmd = "dm_spawnitem it_scroll_110"},
  {name = " BOOK: Zerrikanian Insects", cmd = "dm_spawnitem it_scroll_212"},
  {name = " BOOK: Zeugl Vigor", cmd = "dm_spawnitem it_scroll_158"},

  -- QUEST ITEMS
  {name = " QUEST: Striga Heart", cmd = "dm_spawnitem it_ingr_010"},
  {name = " QUEST: Golem Obsidian Heart", cmd = "dm_spawnitem it_ingr_002"},
  {name = " QUEST: Frightener Eye", cmd = "dm_spawnitem it_ingr_004"},
  {name = " QUEST: Alabaster Figurine", cmd = "dm_spawnitem it_quest_181"},
  {name = " QUEST: Alina's Mirror", cmd = "dm_spawnitem it_quest_176"},
  {name = " QUEST: Alina's Garland", cmd = "dm_spawnitem it_quest185"},
  {name = " QUEST: Angus Key", cmd = "dm_spawnitem it_key_q3016_001"},
  {name = " QUEST: Anti-illusion Philter", cmd = "dm_spawnitem it_quest_136"},
  {name = " QUEST: Arrest Warrant", cmd = "dm_spawnitem it_quest_108"},
  {name = " QUEST: Bandit Key", cmd = "dm_spawnitem it_key_q3016_002"},
  {name = " QUEST: Berengar Medallion", cmd = "dm_spawnitem it_bera_medall"},
  {name = " QUEST: Berengar Notes", cmd = "dm_spawnitem it_quest_164"},
  {name = " QUEST: Cat Harness", cmd = "dm_spawnitem it_quest_196"},
  {name = " QUEST: Dandelion Lute", cmd = "dm_spawnitem it_quest_151"},
  {name = " QUEST: Dice Box", cmd = "dm_spawnitem it_quest_199"},
  {name = " QUEST: Dimetritium Amulet", cmd = "dm_spawnitem it_quest_177"},
  {name = " QUEST: Four-Leaf Clover", cmd = "dm_spawnitem it_quest_195"},
  {name = " QUEST: Glass Vial", cmd = "dm_spawnitem it_quest_191"},
  {name = " QUEST: Glean Enid", cmd = "dm_spawnitem it_quest_135"},
  {name = " QUEST: Gold Bracelet", cmd = "dm_spawnitem it_quest_182"},
  {name = " QUEST: Golden Calf", cmd = "dm_spawnitem it_quest_184"},
  {name = " QUEST: Gramps Diamond", cmd = "dm_spawnitem it_quest_180"},
  {name = " QUEST: Grandma Cordial", cmd = "dm_spawnitem it_quest_158"},
  {name = " QUEST: Grandma Pickle", cmd = "dm_spawnitem it_quest_159"},
  {name = " QUEST: Holy Flame", cmd = "dm_spawnitem it_quest_148"},
  {name = " QUEST: Isa's Beads", cmd = "dm_spawnitem it_quest_149"},
  {name = " QUEST: Kalkstein Notes", cmd = "dm_spawnitem it_quest_229"},
  {name = " QUEST: Salamandra Code Key", cmd = "dm_spawnitem it_quest_165"},
  {name = " QUEST: Lightning Rod", cmd = "dm_spawnitem it_quest_138"},
  {name = " QUEST: List of Suspects", cmd = "dm_spawnitem it_quest_213"},
  {name = " QUEST: Lycanthropy Cure", cmd = "dm_spawnitem it_quest_154"},
  {name = " QUEST: Magic Formula", cmd = "dm_spawnitem it_quset_202"},
  {name = " QUEST: Magic Sensor", cmd = "dm_spawnitem it_quest_178"},
  {name = " QUEST: Mysterious Note", cmd = "dm_spawnitem it_quest_171"},
  {name = " QUEST: Ostrit Journal", cmd = "dm_spawnitem it_quest_189"},
  {name = " QUEST: Potion for Triss", cmd = "dm_spawnitem it_potion_015"},
  {name = " QUEST: Power Stone", cmd = "dm_spawnitem it_key_q3013_001"},
  {name = " QUEST: Priest Staff", cmd = "dm_spawnitem it_quest_186"},
  {name = " QUEST: Psilocybe", cmd = "dm_spawnitem it_quest_170"},
  {name = " QUEST: Receipt", cmd = "dm_spawnitem it_quest_198"},
  {name = " QUEST: Remains Raven Armor", cmd = "dm_spawnitem it_quest_204"},
  {name = " QUEST: Royal Edicts", cmd = "dm_spawnitem it_quest_205"},
  {name = " QUEST: Royal Safe Conduct", cmd = "dm_spawnitem it_quest_168"},
  {name = " QUEST: Salamandra Documents", cmd = "dm_spawnitem it_quest_157"},
  {name = " QUEST: Secret Gates", cmd = "dm_spawnitem it_scroll_008"},
  {name = " QUEST: Seeing Stone", cmd = "dm_spawnitem it_quest_172"},
  {name = " QUEST: Split Salamander", cmd = "dm_spawnitem it_quest_117"},
  {name = " QUEST: St Gregory Litany", cmd = "dm_spawnitem it_quest_201"},
  {name = " QUEST: Teleporting Crystal", cmd = "dm_spawnitem it_quest_214"},
  {name = " QUEST: Lady of Lake Ruby", cmd = "dm_spawnitem it_quest_183"},
  {name = " QUEST: Professor Report", cmd = "dm_spawnitem it_quest_188"},
  {name = " QUEST: Tower Tarot", cmd = "dm_spawnitem it_quest_137"},
  {name = " QUEST: Tower Mage Book", cmd = "dm_spawnitem it_quest_142"},
  {name = " QUEST: Turquoise Necklace", cmd = "dm_spawnitem it_quest_193"},
  {name = " QUEST: Vizima Cemetery Pass", cmd = "dm_spawnitem it_quest_211"},
  {name = " QUEST: Vodyanoi Amulet", cmd = "dm_spawnitem it_quest_150"},
  {name = " QUEST: Vodyanoi Ring", cmd = "dm_spawnitem it_quest_179"},
  {name = " QUEST: Witcher Medallion", cmd = "dm_spawnitem it_quest_163"},
  {name = " QUEST: Wreath Immortelles", cmd = "dm_spawnitem it_quest_192"},
  {name = " QUEST: Yellow Milk", cmd = "dm_spawnitem it_quest_197"},

  -- SEPHIROTS
  {name = " SEPHIROT: Chocc'mah", cmd = "dm_spawnitem it_quest_130"},
  {name = " SEPHIROT: Ghe'vrath", cmd = "dm_spawnitem it_quest_127"},
  {name = " SEPHIROT: Keth'aar", cmd = "dm_spawnitem it_quest_129"},
  {name = " SEPHIROT: Kezah", cmd = "dm_spawnitem it_quest_131"},
  {name = " SEPHIROT: Maal'Kad", cmd = "dm_spawnitem it_quest_125"},
  {name = " SEPHIROT: Neh'tza", cmd = "dm_spawnitem it_quest_134"},
  {name = " SEPHIROT: Oth", cmd = "dm_spawnitem it_quest_128"},
  {name = " SEPHIROT: Tipperath", cmd = "dm_spawnitem it_quest_132"},
  {name = " SEPHIROT: Veen'ah", cmd = "dm_spawnitem it_quest_126"},
  {name = " SEPHIROT: Y'esath", cmd = "dm_spawnitem it_quest_133"},

  -- KEYS
  {name = " KEY: Leuvaarden's Key", cmd = "dm_spawnitem it_key_001"},
  {name = " KEY: Scheffer's Key", cmd = "dm_spawnitem it_key_002"},
  {name = " KEY: Grabek's Key", cmd = "dm_spawnitem it_key_003"},
  {name = " KEY: Pograbek's Key", cmd = "dm_spawnitem it_key_004"},
  {name = " KEY: Reverend's Key", cmd = "dm_spawnitem it_key_005"},
  {name = " KEY: Haren's Key", cmd = "dm_spawnitem it_key_006"},
  {name = " KEY: Ferner's Key", cmd = "dm_spawnitem it_key_007"},
  {name = " KEY: Teterer's Key", cmd = "dm_spawnitem it_key_008"},
  {name = " KEY: Sewer Key", cmd = "dm_spawnitem it_key_022"},
  {name = " KEY: Cemetery Key", cmd = "dm_spawnitem it_key_024"},
  {name = " KEY: Zeugl Key", cmd = "dm_spawnitem key_zeugl"},

  -- INGREDIENTS
  {name = " INGR: Abomination Lymph", cmd = "dm_spawnitem it_ingr_153"},
  {name = " INGR: Albar Crystals", cmd = "dm_spawnitem it_ingr_113"},
  {name = " INGR: Alchemical Paste", cmd = "dm_spawnitem it_ingr_029"},
  {name = " INGR: Alchemists Powder", cmd = "dm_spawnitem it_ingr_034"},
  {name = " INGR: Alghoul Marrow", cmd = "dm_spawnitem it_ingr_168"},
  {name = " INGR: Allspice Root", cmd = "dm_spawnitem it_ingr_056"},
  {name = " INGR: Alp Fangs", cmd = "dm_spawnitem it_ingr_177"},
  {name = " INGR: Archespore Juice", cmd = "dm_spawnitem it_ingr_155"},
  {name = " INGR: Balisse Fruit", cmd = "dm_spawnitem it_ingr_054"},
  {name = " INGR: Bear Fat", cmd = "dm_spawnitem it_ingr_028"},
  {name = " INGR: Beast Fangs", cmd = "dm_spawnitem it_ingr_166"},
  {name = " INGR: Beast Liver", cmd = "dm_spawnitem it_ingr_167"},
  {name = " INGR: Beggartick Blossoms", cmd = "dm_spawnitem it_ingr_061"},
  {name = " INGR: Berbercane Fruit", cmd = "dm_spawnitem it_ingr_069"},
  {name = " INGR: Bloedzuiger Blood", cmd = "dm_spawnitem it_ingr_156"},
  {name = " INGR: Bruxa Blood", cmd = "dm_spawnitem it_ingr_017"},
  {name = " INGR: Bryonia", cmd = "dm_spawnitem it_ingr_067"},
  {name = " INGR: Cadaverine", cmd = "dm_spawnitem it_ingr_151"},
  {name = " INGR: Calcium Equum", cmd = "dm_spawnitem it_ingr_105"},
  {name = " INGR: Celandine", cmd = "dm_spawnitem it_ingr_053"},
  {name = " INGR: Cemetaur Jaw", cmd = "dm_spawnitem it_ingr_178"},
  {name = " INGR: Cockatrice Feather", cmd = "dm_spawnitem it_ingr_001"},
  {name = " INGR: Dagon Secretions", cmd = "dm_spawnitem it_ingr_008"},
  {name = " INGR: Death Dust", cmd = "dm_spawnitem it_ingr_013"},
  {name = " INGR: Devourer Teeth", cmd = "dm_spawnitem it_ingr_174"},
  {name = " INGR: Dog Tallow", cmd = "dm_spawnitem it_ingr_180"},
  {name = " INGR: Drowner Tongue", cmd = "dm_spawnitem it_ingr_162"},
  {name = " INGR: Drowner Brain", cmd = "dm_spawnitem it_ingr_164"},
  {name = " INGR: Ducal Water", cmd = "dm_spawnitem it_ingr_110"},
  {name = " INGR: Echinops Root", cmd = "dm_spawnitem it_ingr_157"},
  {name = " INGR: Ectoplasm", cmd = "dm_spawnitem it_ingr_163"},
  {name = " INGR: Ergot Seeds", cmd = "dm_spawnitem it_ingr_058"},
  {name = " INGR: Feainnewedd", cmd = "dm_spawnitem it_ingr_059"},
  {name = " INGR: Fifth Essence", cmd = "dm_spawnitem it_ingr_109"},
  {name = " INGR: Fools Parsley", cmd = "dm_spawnitem it_ingr_062"},
  {name = " INGR: Garkain Saliva", cmd = "dm_spawnitem it_ingr_171"},
  {name = " INGR: Ghoul Blood", cmd = "dm_spawnitem it_ingr_160"},
  {name = " INGR: Ginata Petals", cmd = "dm_spawnitem it_ingr_073"},
  {name = " INGR: Ginatz Acid", cmd = "dm_spawnitem it_ingr_102"},
  {name = " INGR: Goose Fat", cmd = "dm_spawnitem it_ingr_026"},
  {name = " INGR: Graveir Bone", cmd = "dm_spawnitem it_ingr_159"},
  {name = " INGR: Green Mold", cmd = "dm_spawnitem it_ingr_060"},
  {name = " INGR: Han Fibers", cmd = "dm_spawnitem it_ingr_068"},
  {name = " INGR: Hellebore Petals", cmd = "dm_spawnitem it_ingr_052"},
  {name = " INGR: Honeysuckle", cmd = "dm_spawnitem it_ingr_070"},
  {name = " INGR: Hop Umbels", cmd = "dm_spawnitem it_ingr_066"},
  {name = " INGR: Kikimore Nerve", cmd = "dm_spawnitem it_ingr_014"},
  {name = " INGR: Kikimore Claw", cmd = "dm_spawnitem it_ingr_175"},
  {name = " INGR: Lunar Shards", cmd = "dm_spawnitem it_ingr_115"},
  {name = " INGR: Mandrake Root", cmd = "dm_spawnitem it_ingr_064"},
  {name = " INGR: Mistletoe", cmd = "dm_spawnitem it_ingr_072"},
  {name = " INGR: Mutagen", cmd = "dm_spawnitem it_ingr_179"},
  {name = " INGR: Naezan Salts", cmd = "dm_spawnitem it_ingr_104"},
  {name = " INGR: Optima Mater", cmd = "dm_spawnitem it_ingr_108"},
  {name = " INGR: Ornithosaur Eye", cmd = "dm_spawnitem it_ingr_161"},
  {name = " INGR: Phosphorus", cmd = "dm_spawnitem it_ingr_111"},
  {name = " INGR: Pituitary Gland", cmd = "dm_spawnitem it_ingr_173"},
  {name = " INGR: Powdered Pearl", cmd = "dm_spawnitem it_ingr_106"},
  {name = " INGR: Pyrite", cmd = "dm_spawnitem it_ingr_107"},
  {name = " INGR: Quicksilver", cmd = "dm_spawnitem it_ingr_114"},
  {name = " INGR: Saltpeter", cmd = "dm_spawnitem it_ingr_031"},
  {name = " INGR: Sewant Mushroom", cmd = "dm_spawnitem it_ingr_071"},
  {name = " INGR: Shadow Dust", cmd = "dm_spawnitem it_ingr_016"},
  {name = " INGR: Shimmering Dust", cmd = "dm_spawnitem it_ingr_015"},
  {name = " INGR: Skullhead Talon", cmd = "dm_spawnitem it_ingr_005"},
  {name = " INGR: Spores", cmd = "dm_spawnitem it_ingr_152"},
  {name = " INGR: Stammelford Dust", cmd = "dm_spawnitem it_ingr_032"},
  {name = " INGR: Stones of Ys", cmd = "dm_spawnitem it_ingr_012"},
  {name = " INGR: Suet", cmd = "dm_spawnitem it_ingr_027"},
  {name = " INGR: Sulfur", cmd = "dm_spawnitem it_ingr_101"},
  {name = " INGR: Tendons", cmd = "dm_spawnitem it_ingr_169"},
  {name = " INGR: Toxin", cmd = "dm_spawnitem it_ingr_172"},
  {name = " INGR: Tracheae", cmd = "dm_spawnitem it_ingr_176"},
  {name = " INGR: Vapors of Hunt", cmd = "dm_spawnitem it_ingr_011"},
  {name = " INGR: Venom Glands", cmd = "dm_spawnitem it_ingr_170"},
  {name = " INGR: Verbena", cmd = "dm_spawnitem it_ingr_065"},
  {name = " INGR: Vodyanoi Bladder", cmd = "dm_spawnitem it_ingr_165"},
  {name = " INGR: Vodyanoi Scales", cmd = "dm_spawnitem it_ingr_154"},
  {name = " INGR: Werewolf Fur", cmd = "dm_spawnitem it_ingr_007"},
  {name = " INGR: White Myrtle", cmd = "dm_spawnitem it_ingr_051"},
  {name = " INGR: White Vinegar", cmd = "dm_spawnitem it_ingr_112"},
  {name = " INGR: Wine Stone", cmd = "dm_spawnitem it_ingr_103"},
  {name = " INGR: Wing Membrane", cmd = "dm_spawnitem it_ingr_158"},
  {name = " INGR: Wolf Aloe", cmd = "dm_spawnitem it_ingr_063"},
  {name = " INGR: Wolfsbane", cmd = "dm_spawnitem it_ingr_057"},
  {name = " INGR: Zerrikanian Mix", cmd = "dm_spawnitem it_ingr_033"},
  {name = " INGR: Zeugl Venom", cmd = "dm_spawnitem it_ingr_006"},

  -- DRINKS
  {name = " DRINK: Alcohest", cmd = "dm_spawnitem it_drink_050"},
  {name = " DRINK: Apple Juice", cmd = "dm_spawnitem it_drink_202"},
  {name = " DRINK: Azoth", cmd = "dm_spawnitem it_drink_051"},
  {name = " DRINK: Beauclair White", cmd = "dm_spawnitem it_drink_007"},
  {name = " DRINK: Bottled Water", cmd = "dm_spawnitem it_drink_201"},
  {name = " DRINK: Cherry Cordial", cmd = "dm_spawnitem it_drink_031"},
  {name = " DRINK: Cintrian Faro", cmd = "dm_spawnitem it_drink_005"},
  {name = " DRINK: Cow Milk", cmd = "dm_spawnitem it_drink_205"},
  {name = " DRINK: Dwarven Spirit", cmd = "dm_spawnitem it_drink_030"},
  {name = " DRINK: Goat Milk", cmd = "dm_spawnitem it_drink_204"},
  {name = " DRINK: Kaedwenian Stout", cmd = "dm_spawnitem it_drink_002"},
  {name = " DRINK: Local Pepper Vodka", cmd = "dm_spawnitem it_drink_020"},
  {name = " DRINK: Mahakaman Mead", cmd = "dm_spawnitem it_drink_009"},
  {name = " DRINK: Mandrake Cordial", cmd = "dm_spawnitem it_drink_042"},
  {name = " DRINK: Mettina Rose", cmd = "dm_spawnitem it_drink_008"},
  {name = " DRINK: Nilfgaard Lemon", cmd = "dm_spawnitem it_drink_021"},
  {name = " DRINK: Plum Cordial", cmd = "dm_spawnitem it_drink_032"},
  {name = " DRINK: Raspberry Juice", cmd = "dm_spawnitem it_drink_203"},
  {name = " DRINK: Redanian Herbal", cmd = "dm_spawnitem it_drink_024"},
  {name = " DRINK: Redanian Lager", cmd = "dm_spawnitem it_drink_004"},
  {name = " DRINK: Rivian Kriek", cmd = "dm_spawnitem it_drink_003"},
  {name = " DRINK: Sodden Mead", cmd = "dm_spawnitem it_drink_010"},
  {name = " DRINK: Soldier's Hooch", cmd = "dm_spawnitem it_drink_023"},
  {name = " DRINK: Temerian Rye", cmd = "dm_spawnitem it_drink_022"},
  {name = " DRINK: Temerian Spirit", cmd = "dm_spawnitem it_drink_033"},
  {name = " DRINK: Toussaint Red", cmd = "dm_spawnitem it_drink_006"},
  {name = " DRINK: Viziman Champion", cmd = "dm_spawnitem it_drink_001"},
  {name = " DRINK: Wormwood Spirit", cmd = "dm_spawnitem it_drink_041"},
  {name = " DRINK: Wyvern Blood Spirit", cmd = "dm_spawnitem it_drink_040"},
  {name = " DRINK: Zerrikanian Spirit", cmd = "dm_spawnitem it_drink_034"},

  -- FOOD
  {name = " FOOD: Bread", cmd = "dm_spawnitem it_food_007"},
  {name = " FOOD: Bun", cmd = "dm_spawnitem it_food_008"},
  {name = " FOOD: Chicken", cmd = "dm_spawnitem it_food_011"},
  {name = " FOOD: Chicken Leg", cmd = "dm_spawnitem it_food_006"},
  {name = " FOOD: Dried Fruit", cmd = "dm_spawnitem it_food_019"},
  {name = " FOOD: Fish", cmd = "dm_spawnitem it_food_023"},
  {name = " FOOD: Honeycomb", cmd = "dm_spawnitem it_food_001"},
  {name = " FOOD: Mutton Leg", cmd = "dm_spawnitem it_food_005"},
  {name = " FOOD: Pork", cmd = "dm_spawnitem it_food_012"},
  {name = " FOOD: Watermelon", cmd = "dm_spawnitem it_food_013"},

  -- JEWELRY
  {name = " RING: Silver Ring", cmd = "dm_spawnitem it_ring_001"},
  {name = " RING: Gold Ring", cmd = "dm_spawnitem it_ring_004"},
  {name = " RING: Gold Signet Ring", cmd = "dm_spawnitem it_ring_009"},
  {name = " RING: Eternal Fire Ring", cmd = "dm_spawnitem it_ring_011"},
  {name = " RING: City Guard Ring", cmd = "dm_spawnitem it_ring_012"},
  {name = " NECKLACE: Silver Necklace", cmd = "dm_spawnitem it_neckl_001"},
  {name = " NECKLACE: Gold Necklace", cmd = "dm_spawnitem it_neckl_003"},
  {name = " GEM: Amber", cmd = "dm_spawnitem it_gem_001"},
  {name = " GEM: Sapphire", cmd = "dm_spawnitem it_gem_002"},
  {name = " GEM: Ruby", cmd = "dm_spawnitem it_gem_003"},
  {name = " GEM: Diamond", cmd = "dm_spawnitem it_gem_004"}
}
